import type { Metadata } from "next";
import { AppSidebar } from "@/components/AppSidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";

import { getApiKey } from "@/util/cookies";
import { redirect } from "next/navigation";
import { getFactionInfo } from "./crime-stats/actions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const apiKey = await getApiKey();

  if (!apiKey) {
    redirect("/api-key");
  }

  const factionInfo = await getFactionInfo();

  return (
    <SidebarProvider>
      <AppSidebar
        factionName={factionInfo.name}
        tagImage={factionInfo.tag_image}
        rankName={factionInfo.rank.name}
      />
      <SidebarInset>
        <header className="px-4 py-2">
          <SidebarTrigger className="-ml-1" />
        </header>
        {children}
      </SidebarInset>
    </SidebarProvider>
  );
}
